-- Clan card requests and one-way card gifts with server-enforced daily quota.
-- Transfers preserve the complete card snapshot (including mastery level/XP) and move ownership atomically.

create table if not exists public.clan_card_requests (
    id uuid primary key default gen_random_uuid(),
    clan_id uuid not null references public.clans(id) on delete cascade,
    user_id uuid not null references public.profiles(id) on delete cascade,
    card_name text not null check (char_length(btrim(card_name)) between 1 and 100),
    status text not null default 'open' check (status in ('open', 'fulfilled', 'cancelled')),
    fulfilled_by uuid references public.profiles(id) on delete set null,
    created_at timestamptz not null default now(),
    fulfilled_at timestamptz
);

create unique index if not exists clan_card_requests_one_open_per_card_idx
    on public.clan_card_requests (clan_id, user_id, card_name)
    where status = 'open';
create index if not exists clan_card_requests_clan_status_created_idx
    on public.clan_card_requests (clan_id, status, created_at desc);

create table if not exists public.player_card_inventory (
    card_uid uuid primary key,
    owner_id uuid not null references public.profiles(id) on delete cascade,
    card_data jsonb not null check (jsonb_typeof(card_data) = 'object'),
    pending_delivery boolean not null default false,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);
create index if not exists player_card_inventory_owner_idx
    on public.player_card_inventory (owner_id, pending_delivery);

create table if not exists public.clan_card_gift_daily (
    sender_id uuid not null references public.profiles(id) on delete cascade,
    utc_day date not null,
    gift_count smallint not null default 0 check (gift_count between 0 and 3),
    primary key (sender_id, utc_day)
);

create table if not exists public.clan_card_gifts (
    id bigint generated by default as identity primary key,
    clan_id uuid references public.clans(id) on delete set null,
    request_id uuid references public.clan_card_requests(id) on delete set null,
    card_uid uuid not null references public.player_card_inventory(card_uid) on delete restrict,
    sender_id uuid not null references public.profiles(id) on delete cascade,
    recipient_id uuid not null references public.profiles(id) on delete cascade,
    card_name text not null,
    rarity text not null,
    mastery_level smallint not null check (mastery_level between 1 and 7),
    created_at timestamptz not null default now()
);
create index if not exists clan_card_gifts_recipient_created_idx
    on public.clan_card_gifts (recipient_id, created_at desc);

alter table public.clan_card_requests enable row level security;
alter table public.player_card_inventory enable row level security;
alter table public.clan_card_gift_daily enable row level security;
alter table public.clan_card_gifts enable row level security;

revoke all on table public.clan_card_requests from anon, authenticated;
revoke all on table public.player_card_inventory from anon, authenticated;
revoke all on table public.clan_card_gift_daily from anon, authenticated;
revoke all on table public.clan_card_gifts from anon, authenticated;
grant select on table public.clan_card_requests, public.clan_card_gifts to authenticated;

drop policy if exists clan_card_requests_read_members on public.clan_card_requests;
create policy clan_card_requests_read_members
on public.clan_card_requests for select to authenticated
using (
    exists (
        select 1 from public.clan_members as m
        where m.clan_id = clan_card_requests.clan_id
          and m.user_id = (select auth.uid())
    )
);

drop policy if exists clan_card_gifts_read_participants on public.clan_card_gifts;
create policy clan_card_gifts_read_participants
on public.clan_card_gifts for select to authenticated
using (
    sender_id = (select auth.uid())
    or recipient_id = (select auth.uid())
);

create or replace function public.sync_clan_card_inventory(p_cards jsonb)
returns table (result_card_uid uuid, ownership_status text)
language plpgsql
security definer
set search_path = ''
as $$
declare
    v_user_id uuid := auth.uid();
    v_item jsonb;
    v_card_uid uuid;
    v_card_name text;
    v_rarity text;
    v_mastery integer;
    v_owner_id uuid;
begin
    if v_user_id is null then
        raise exception 'auth_required' using errcode = '28000';
    end if;
    if p_cards is null or jsonb_typeof(p_cards) <> 'array' then
        raise exception 'card_inventory_invalid' using errcode = '22023';
    end if;
    if jsonb_array_length(p_cards) > 3000 then
        raise exception 'card_inventory_too_large' using errcode = '22023';
    end if;

    for v_item in select e.value from pg_catalog.jsonb_array_elements(p_cards) as e(value)
    loop
        if jsonb_typeof(v_item) <> 'object' or pg_catalog.pg_column_size(v_item) > 32768 then
            raise exception 'card_inventory_invalid' using errcode = '22023';
        end if;

        if coalesce(v_item->>'_mbCardUid', '') !~* '^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$' then
            raise exception 'card_inventory_invalid' using errcode = '22023';
        end if;
        v_card_uid := (v_item->>'_mbCardUid')::uuid;
        v_card_name := btrim(coalesce(v_item->>'name', ''));
        v_rarity := coalesce(v_item->>'rarity', '');
        v_mastery := coalesce(nullif(v_item->>'mastery', '')::integer, 1);

        if char_length(v_card_name) < 1 or char_length(v_card_name) > 100
           or v_mastery < 1 or v_mastery > 7 then
            raise exception 'card_inventory_invalid' using errcode = '22023';
        end if;

        -- Register transferable rarities; keep already registered rows updated even if
        -- a card later becomes ineligible, so an old snapshot cannot bypass the rarity cap.
        if v_rarity in ('Обычная', 'Редкая', 'Сверх редкая', 'Эпик', 'Мифическая', 'Легендарная') then
            insert into public.player_card_inventory (card_uid, owner_id, card_data, pending_delivery)
            values (v_card_uid, v_user_id, v_item, false)
            on conflict (card_uid) do update
                set card_data = excluded.card_data,
                    updated_at = pg_catalog.now()
                where public.player_card_inventory.owner_id = v_user_id
                  and public.player_card_inventory.pending_delivery = false;
        else
            update public.player_card_inventory as i
            set card_data = v_item, updated_at = pg_catalog.now()
            where i.card_uid = v_card_uid
              and i.owner_id = v_user_id
              and i.pending_delivery = false;
        end if;

        select i.owner_id into v_owner_id
        from public.player_card_inventory as i
        where i.card_uid = v_card_uid;

        result_card_uid := v_card_uid;
        if not found then
            ownership_status := 'untracked';
        elsif v_owner_id = v_user_id then
            ownership_status := 'owned';
        else
            ownership_status := 'transferred';
        end if;
        return next;
    end loop;
end;
$$;

create or replace function public.request_clan_card(p_card_name text)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
    v_user_id uuid := auth.uid();
    v_clan_id uuid;
    v_name text := btrim(coalesce(p_card_name, ''));
    v_request_id uuid;
    v_open_count integer;
begin
    if v_user_id is null then
        raise exception 'auth_required' using errcode = '28000';
    end if;
    if char_length(v_name) < 1 or char_length(v_name) > 100 then
        raise exception 'card_request_invalid' using errcode = '22023';
    end if;

    select m.clan_id into v_clan_id
    from public.clan_members as m
    where m.user_id = v_user_id
    for update;
    if not found then
        raise exception 'not_in_clan' using errcode = 'P0002';
    end if;

    select count(*) into v_open_count
    from public.clan_card_requests as r
    where r.clan_id = v_clan_id
      and r.user_id = v_user_id
      and r.status = 'open';
    if v_open_count >= 5 then
        raise exception 'card_request_limit' using errcode = '22023';
    end if;

    insert into public.clan_card_requests (clan_id, user_id, card_name)
    values (v_clan_id, v_user_id, v_name)
    returning id into v_request_id;
    return v_request_id;
exception
    when unique_violation then
        raise exception 'card_request_duplicate' using errcode = '23505';
end;
$$;

create or replace function public.cancel_clan_card_request(p_request_id uuid)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
    v_user_id uuid := auth.uid();
begin
    if v_user_id is null then
        raise exception 'auth_required' using errcode = '28000';
    end if;

    update public.clan_card_requests as r
    set status = 'cancelled'
    where r.id = p_request_id
      and r.user_id = v_user_id
      and r.status = 'open';

    if not found then
        raise exception 'card_request_not_found' using errcode = 'P0002';
    end if;
end;
$$;

create or replace function public.get_clan_card_gift_status()
returns table (gifts_used integer, gifts_remaining integer)
language plpgsql
security definer
set search_path = ''
as $$
declare
    v_user_id uuid := auth.uid();
    v_used integer := 0;
    v_day date := (pg_catalog.now() at time zone 'UTC')::date;
begin
    if v_user_id is null then
        raise exception 'auth_required' using errcode = '28000';
    end if;

    select d.gift_count into v_used
    from public.clan_card_gift_daily as d
    where d.sender_id = v_user_id and d.utc_day = v_day;

    v_used := coalesce(v_used, 0);
    gifts_used := v_used;
    gifts_remaining := greatest(0, 3 - v_used);
    return next;
end;
$$;

create or replace function public.get_pending_clan_card_gifts()
returns table (card_uid uuid, card_data jsonb)
language plpgsql
security definer
set search_path = ''
as $$
declare
    v_user_id uuid := auth.uid();
begin
    if v_user_id is null then
        raise exception 'auth_required' using errcode = '28000';
    end if;

    return query
    select i.card_uid, i.card_data
    from public.player_card_inventory as i
    where i.owner_id = v_user_id
      and i.pending_delivery = true
    order by i.updated_at asc;
end;
$$;

create or replace function public.acknowledge_clan_card_gifts(p_card_uids uuid[])
returns integer
language plpgsql
security definer
set search_path = ''
as $$
declare
    v_user_id uuid := auth.uid();
    v_count integer;
begin
    if v_user_id is null then
        raise exception 'auth_required' using errcode = '28000';
    end if;

    update public.player_card_inventory as i
    set pending_delivery = false, updated_at = pg_catalog.now()
    where i.owner_id = v_user_id
      and i.pending_delivery = true
      and i.card_uid = any(coalesce(p_card_uids, array[]::uuid[]));
    get diagnostics v_count = row_count;
    return v_count;
end;
$$;

create or replace function public.transfer_clan_card(p_request_id uuid, p_card_uid uuid)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
    v_user_id uuid := auth.uid();
    v_request record;
    v_card_data jsonb;
    v_card_name text;
    v_rarity text;
    v_mastery integer;
    v_day date := (pg_catalog.now() at time zone 'UTC')::date;
    v_used integer;
    v_gift_id bigint;
begin
    if v_user_id is null then
        raise exception 'auth_required' using errcode = '28000';
    end if;

    select r.id, r.clan_id, r.user_id, r.card_name
    into v_request
    from public.clan_card_requests as r
    where r.id = p_request_id and r.status = 'open'
    for update;
    if not found then
        raise exception 'card_request_not_found' using errcode = 'P0002';
    end if;
    if v_request.user_id = v_user_id then
        raise exception 'card_request_own' using errcode = '22023';
    end if;

    if not exists (
        select 1 from public.clan_members as m
        where m.clan_id = v_request.clan_id and m.user_id = v_user_id
    ) or not exists (
        select 1 from public.clan_members as m
        where m.clan_id = v_request.clan_id and m.user_id = v_request.user_id
    ) then
        raise exception 'not_clan_member' using errcode = '42501';
    end if;

    select i.card_data into v_card_data
    from public.player_card_inventory as i
    where i.card_uid = p_card_uid
      and i.owner_id = v_user_id
      and i.pending_delivery = false
    for update;
    if not found then
        raise exception 'card_not_owned' using errcode = '42501';
    end if;

    v_card_name := btrim(coalesce(v_card_data->>'name', ''));
    v_rarity := coalesce(v_card_data->>'rarity', '');
    v_mastery := coalesce(nullif(v_card_data->>'mastery', '')::integer, 1);

    if v_rarity not in ('Обычная', 'Редкая', 'Сверх редкая', 'Эпик', 'Мифическая', 'Легендарная') then
        raise exception 'card_rarity_blocked' using errcode = '42501';
    end if;
    if v_card_name <> v_request.card_name then
        raise exception 'card_request_name_mismatch' using errcode = '22023';
    end if;

    if v_mastery = 7 and exists (
        select 1
        from public.player_card_inventory as i
        where i.owner_id = v_request.user_id
          and i.card_uid <> p_card_uid
          and coalesce(nullif(i.card_data->>'mastery', '')::integer, 1) >= 7
    ) then
        raise exception 'recipient_level7_conflict' using errcode = '22023';
    end if;

    insert into public.clan_card_gift_daily (sender_id, utc_day, gift_count)
    values (v_user_id, v_day, 0)
    on conflict (sender_id, utc_day) do nothing;

    select d.gift_count into v_used
    from public.clan_card_gift_daily as d
    where d.sender_id = v_user_id and d.utc_day = v_day
    for update;
    if v_used >= 3 then
        raise exception 'daily_card_gift_limit' using errcode = '22023';
    end if;

    update public.player_card_inventory as i
    set owner_id = v_request.user_id,
        pending_delivery = true,
        updated_at = pg_catalog.now()
    where i.card_uid = p_card_uid
      and i.owner_id = v_user_id
      and i.pending_delivery = false;
    if not found then
        raise exception 'card_not_owned' using errcode = '42501';
    end if;

    update public.clan_card_requests as r
    set status = 'fulfilled',
        fulfilled_by = v_user_id,
        fulfilled_at = pg_catalog.now()
    where r.id = v_request.id
      and r.status = 'open';

    update public.clan_card_gift_daily as d
    set gift_count = d.gift_count + 1
    where d.sender_id = v_user_id and d.utc_day = v_day;

    insert into public.clan_card_gifts (
        clan_id, request_id, card_uid, sender_id, recipient_id,
        card_name, rarity, mastery_level
    )
    values (
        v_request.clan_id, v_request.id, p_card_uid, v_user_id, v_request.user_id,
        v_card_name, v_rarity, v_mastery
    )
    returning id into v_gift_id;

    return pg_catalog.jsonb_build_object(
        'gift_id', v_gift_id,
        'card_uid', p_card_uid,
        'card_name', v_card_name,
        'rarity', v_rarity,
        'mastery_level', v_mastery
    );
end;
$$;

revoke all on function public.sync_clan_card_inventory(jsonb) from public, anon, authenticated;
revoke all on function public.request_clan_card(text) from public, anon, authenticated;
revoke all on function public.cancel_clan_card_request(uuid) from public, anon, authenticated;
revoke all on function public.get_clan_card_gift_status() from public, anon, authenticated;
revoke all on function public.get_pending_clan_card_gifts() from public, anon, authenticated;
revoke all on function public.acknowledge_clan_card_gifts(uuid[]) from public, anon, authenticated;
revoke all on function public.transfer_clan_card(uuid, uuid) from public, anon, authenticated;

grant execute on function public.sync_clan_card_inventory(jsonb) to authenticated;
grant execute on function public.request_clan_card(text) to authenticated;
grant execute on function public.cancel_clan_card_request(uuid) to authenticated;
grant execute on function public.get_clan_card_gift_status() to authenticated;
grant execute on function public.get_pending_clan_card_gifts() to authenticated;
grant execute on function public.acknowledge_clan_card_gifts(uuid[]) to authenticated;
grant execute on function public.transfer_clan_card(uuid, uuid) to authenticated;

-- Realtime notifications allow the recipient's online game to receive gifts immediately.
do $$
begin
    if exists (select 1 from pg_publication where pubname = 'supabase_realtime')
       and not exists (
           select 1 from pg_publication_tables
           where pubname = 'supabase_realtime'
             and schemaname = 'public'
             and tablename = 'clan_card_gifts'
       ) then
        execute 'alter publication supabase_realtime add table public.clan_card_gifts';
    end if;
end;
$$;
