-- Multiverse Battle: editable online profiles, public profile stats and private clan chat.
-- Existing clan tables and RPC functions stay intact.

alter table public.profiles
    add column if not exists avatar_name text not null default 'Дио'
        check (char_length(avatar_name) between 1 and 80),
    add column if not exists description text not null default ''
        check (char_length(description) <= 280),
    add column if not exists total_wins bigint not null default 0
        check (total_wins between 0 and 1000000000),
    add column if not exists highest_wave integer not null default 1
        check (highest_wave between 1 and 1000000000),
    add column if not exists rebirth_count integer not null default 0
        check (rebirth_count between 0 and 1000000),
    add column if not exists cards_collected bigint not null default 0
        check (cards_collected between 0 and 1000000000),
    add column if not exists bosses_defeated integer not null default 0
        check (bosses_defeated between 0 and 1000000),
    add column if not exists total_clicks bigint not null default 0
        check (total_clicks between 0 and 1000000000),
    add column if not exists updated_at timestamptz not null default now();

-- Replace the original one-column grant with an explicit allowlist of editable profile/stat columns.
revoke update (display_name) on table public.profiles from authenticated;
grant select on table public.profiles to authenticated;
grant update (
    display_name,
    avatar_name,
    description,
    total_wins,
    highest_wave,
    rebirth_count,
    cards_collected,
    bosses_defeated,
    total_clicks
) on table public.profiles to authenticated;

create or replace function public.touch_profile_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
    new.updated_at := pg_catalog.now();
    return new;
end;
$$;

drop trigger if exists profiles_touch_updated_at on public.profiles;
create trigger profiles_touch_updated_at
before update on public.profiles
for each row execute function public.touch_profile_updated_at();

revoke all on function public.touch_profile_updated_at() from public, anon, authenticated;

create table if not exists public.clan_messages (
    id bigint generated by default as identity primary key,
    clan_id uuid not null references public.clans(id) on delete cascade,
    user_id uuid not null references public.profiles(id) on delete cascade,
    message text not null check (
        char_length(btrim(message)) between 1 and 500
    ),
    created_at timestamptz not null default now()
);

create index if not exists clan_messages_clan_created_idx
    on public.clan_messages (clan_id, created_at desc);

alter table public.clan_messages enable row level security;
revoke all on table public.clan_messages from anon, authenticated;
grant select, insert on table public.clan_messages to authenticated;

drop policy if exists clan_messages_read_members on public.clan_messages;
create policy clan_messages_read_members
on public.clan_messages for select to authenticated
using (
    exists (
        select 1
        from public.clan_members as m
        where m.clan_id = clan_messages.clan_id
          and m.user_id = (select auth.uid())
    )
);

drop policy if exists clan_messages_send_members on public.clan_messages;
create policy clan_messages_send_members
on public.clan_messages for insert to authenticated
with check (
    user_id = (select auth.uid())
    and exists (
        select 1
        from public.clan_members as m
        where m.clan_id = clan_messages.clan_id
          and m.user_id = (select auth.uid())
    )
);

-- Enable realtime inserts for clan members using the existing Supabase Realtime publication.
do $$
begin
    if exists (select 1 from pg_publication where pubname = 'supabase_realtime')
       and not exists (
           select 1 from pg_publication_tables
           where pubname = 'supabase_realtime'
             and schemaname = 'public'
             and tablename = 'clan_messages'
       ) then
        execute 'alter publication supabase_realtime add table public.clan_messages';
    end if;
end;
$$;
