-- Public community chat for authenticated Multiverse Battle players.
create table if not exists public.global_chat_messages (
    id bigint generated by default as identity primary key,
    user_id uuid not null references public.profiles(id) on delete cascade,
    sender_name text not null check (char_length(btrim(sender_name)) between 1 and 24),
    avatar_name text not null default 'Дио' check (char_length(btrim(avatar_name)) between 1 and 80),
    message text not null check (char_length(btrim(message)) between 1 and 300),
    created_at timestamptz not null default pg_catalog.clock_timestamp()
);

create index if not exists global_chat_messages_created_idx
    on public.global_chat_messages (created_at desc);
create index if not exists global_chat_messages_user_created_idx
    on public.global_chat_messages (user_id, created_at desc);

alter table public.global_chat_messages enable row level security;
revoke all on table public.global_chat_messages from public, anon, authenticated;
grant select on table public.global_chat_messages to authenticated;

drop policy if exists global_chat_read_authenticated on public.global_chat_messages;
create policy global_chat_read_authenticated
on public.global_chat_messages for select to authenticated
using ((select auth.uid()) is not null);

create or replace function public.mb_send_global_chat_message(p_message text)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
    v_uid uuid := auth.uid();
    v_message text := btrim(coalesce(p_message, ''));
    v_sender_name text;
    v_avatar_name text;
    v_recent_count integer;
    v_row record;
begin
    if v_uid is null then
        raise exception 'global_chat_auth_required';
    end if;
    if v_message = '' then
        raise exception 'global_chat_empty';
    end if;
    if char_length(v_message) > 300 then
        raise exception 'global_chat_too_long';
    end if;

    -- Serialize concurrent sends from the same account so the rate limit cannot
    -- be bypassed by submitting several requests at once.
    perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended(v_uid::text, 0));

    select p.display_name, p.avatar_name
      into v_sender_name, v_avatar_name
      from public.profiles as p
     where p.id = v_uid;
    if not found then
        raise exception 'profile_not_found';
    end if;

    select count(*)::integer
      into v_recent_count
      from public.global_chat_messages as m
     where m.user_id = v_uid
       and m.created_at > pg_catalog.clock_timestamp() - interval '10 seconds';

    if v_recent_count >= 5 then
        raise exception 'global_chat_rate_limited';
    end if;

    insert into public.global_chat_messages (user_id, sender_name, avatar_name, message)
    values (v_uid, coalesce(nullif(btrim(v_sender_name), ''), 'Игрок'), coalesce(nullif(btrim(v_avatar_name), ''), 'Дио'), v_message)
    returning id, user_id, sender_name, avatar_name, message, created_at into v_row;

    return jsonb_build_object(
        'id', v_row.id,
        'user_id', v_row.user_id,
        'sender_name', v_row.sender_name,
        'avatar_name', v_row.avatar_name,
        'message', v_row.message,
        'created_at', v_row.created_at
    );
end;
$$;

revoke all on function public.mb_send_global_chat_message(text) from public, anon;
grant execute on function public.mb_send_global_chat_message(text) to authenticated;

do $$
begin
    if exists (select 1 from pg_catalog.pg_publication where pubname = 'supabase_realtime')
       and not exists (
           select 1 from pg_catalog.pg_publication_tables
            where pubname = 'supabase_realtime'
              and schemaname = 'public'
              and tablename = 'global_chat_messages'
       ) then
        execute 'alter publication supabase_realtime add table public.global_chat_messages';
    end if;
end;
$$;
